/*
FiftyTen Service Contracts

Common API contracts for FiftyTen microservices

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// checks if the ApiTasksPostRequestOneOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiTasksPostRequestOneOf{}

// ApiTasksPostRequestOneOf struct for ApiTasksPostRequestOneOf
type ApiTasksPostRequestOneOf struct {
	Tasks []Task `json:"tasks,omitempty"`
}

// NewApiTasksPostRequestOneOf instantiates a new ApiTasksPostRequestOneOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiTasksPostRequestOneOf() *ApiTasksPostRequestOneOf {
	this := ApiTasksPostRequestOneOf{}
	return &this
}

// NewApiTasksPostRequestOneOfWithDefaults instantiates a new ApiTasksPostRequestOneOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiTasksPostRequestOneOfWithDefaults() *ApiTasksPostRequestOneOf {
	this := ApiTasksPostRequestOneOf{}
	return &this
}

// GetTasks returns the Tasks field value if set, zero value otherwise.
func (o *ApiTasksPostRequestOneOf) GetTasks() []Task {
	if o == nil || IsNil(o.Tasks) {
		var ret []Task
		return ret
	}
	return o.Tasks
}

// GetTasksOk returns a tuple with the Tasks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiTasksPostRequestOneOf) GetTasksOk() ([]Task, bool) {
	if o == nil || IsNil(o.Tasks) {
		return nil, false
	}
	return o.Tasks, true
}

// HasTasks returns a boolean if a field has been set.
func (o *ApiTasksPostRequestOneOf) HasTasks() bool {
	if o != nil && !IsNil(o.Tasks) {
		return true
	}

	return false
}

// SetTasks gets a reference to the given []Task and assigns it to the Tasks field.
func (o *ApiTasksPostRequestOneOf) SetTasks(v []Task) {
	o.Tasks = v
}

func (o ApiTasksPostRequestOneOf) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiTasksPostRequestOneOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Tasks) {
		toSerialize["tasks"] = o.Tasks
	}
	return toSerialize, nil
}

type NullableApiTasksPostRequestOneOf struct {
	value *ApiTasksPostRequestOneOf
	isSet bool
}

func (v NullableApiTasksPostRequestOneOf) Get() *ApiTasksPostRequestOneOf {
	return v.value
}

func (v *NullableApiTasksPostRequestOneOf) Set(val *ApiTasksPostRequestOneOf) {
	v.value = val
	v.isSet = true
}

func (v NullableApiTasksPostRequestOneOf) IsSet() bool {
	return v.isSet
}

func (v *NullableApiTasksPostRequestOneOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiTasksPostRequestOneOf(val *ApiTasksPostRequestOneOf) *NullableApiTasksPostRequestOneOf {
	return &NullableApiTasksPostRequestOneOf{value: val, isSet: true}
}

func (v NullableApiTasksPostRequestOneOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiTasksPostRequestOneOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
