/*
FiftyTen Service Contracts

Common API contracts for FiftyTen microservices

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CryptoMarketContext type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CryptoMarketContext{}

// CryptoMarketContext struct for CryptoMarketContext
type CryptoMarketContext struct {
	Interval Interval `json:"interval"`
	// Category of the market
	MarketCategory string           `json:"marketCategory"`
	ExchangeType   ExchangeType     `json:"exchangeType"`
	Symbol         Symbol           `json:"symbol"`
	MarketType     CryptoMarketType `json:"marketType"`
}

type _CryptoMarketContext CryptoMarketContext

// NewCryptoMarketContext instantiates a new CryptoMarketContext object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCryptoMarketContext(interval Interval, marketCategory string, exchangeType ExchangeType, symbol Symbol, marketType CryptoMarketType) *CryptoMarketContext {
	this := CryptoMarketContext{}
	this.Interval = interval
	this.MarketCategory = marketCategory
	this.ExchangeType = exchangeType
	this.Symbol = symbol
	this.MarketType = marketType
	return &this
}

// NewCryptoMarketContextWithDefaults instantiates a new CryptoMarketContext object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCryptoMarketContextWithDefaults() *CryptoMarketContext {
	this := CryptoMarketContext{}
	return &this
}

// GetInterval returns the Interval field value
func (o *CryptoMarketContext) GetInterval() Interval {
	if o == nil {
		var ret Interval
		return ret
	}

	return o.Interval
}

// GetIntervalOk returns a tuple with the Interval field value
// and a boolean to check if the value has been set.
func (o *CryptoMarketContext) GetIntervalOk() (*Interval, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Interval, true
}

// SetInterval sets field value
func (o *CryptoMarketContext) SetInterval(v Interval) {
	o.Interval = v
}

// GetMarketCategory returns the MarketCategory field value
func (o *CryptoMarketContext) GetMarketCategory() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MarketCategory
}

// GetMarketCategoryOk returns a tuple with the MarketCategory field value
// and a boolean to check if the value has been set.
func (o *CryptoMarketContext) GetMarketCategoryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MarketCategory, true
}

// SetMarketCategory sets field value
func (o *CryptoMarketContext) SetMarketCategory(v string) {
	o.MarketCategory = v
}

// GetExchangeType returns the ExchangeType field value
func (o *CryptoMarketContext) GetExchangeType() ExchangeType {
	if o == nil {
		var ret ExchangeType
		return ret
	}

	return o.ExchangeType
}

// GetExchangeTypeOk returns a tuple with the ExchangeType field value
// and a boolean to check if the value has been set.
func (o *CryptoMarketContext) GetExchangeTypeOk() (*ExchangeType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExchangeType, true
}

// SetExchangeType sets field value
func (o *CryptoMarketContext) SetExchangeType(v ExchangeType) {
	o.ExchangeType = v
}

// GetSymbol returns the Symbol field value
func (o *CryptoMarketContext) GetSymbol() Symbol {
	if o == nil {
		var ret Symbol
		return ret
	}

	return o.Symbol
}

// GetSymbolOk returns a tuple with the Symbol field value
// and a boolean to check if the value has been set.
func (o *CryptoMarketContext) GetSymbolOk() (*Symbol, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Symbol, true
}

// SetSymbol sets field value
func (o *CryptoMarketContext) SetSymbol(v Symbol) {
	o.Symbol = v
}

// GetMarketType returns the MarketType field value
func (o *CryptoMarketContext) GetMarketType() CryptoMarketType {
	if o == nil {
		var ret CryptoMarketType
		return ret
	}

	return o.MarketType
}

// GetMarketTypeOk returns a tuple with the MarketType field value
// and a boolean to check if the value has been set.
func (o *CryptoMarketContext) GetMarketTypeOk() (*CryptoMarketType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MarketType, true
}

// SetMarketType sets field value
func (o *CryptoMarketContext) SetMarketType(v CryptoMarketType) {
	o.MarketType = v
}

func (o CryptoMarketContext) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CryptoMarketContext) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["interval"] = o.Interval
	toSerialize["marketCategory"] = o.MarketCategory
	toSerialize["exchangeType"] = o.ExchangeType
	toSerialize["symbol"] = o.Symbol
	toSerialize["marketType"] = o.MarketType
	return toSerialize, nil
}

func (o *CryptoMarketContext) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"interval",
		"marketCategory",
		"exchangeType",
		"symbol",
		"marketType",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCryptoMarketContext := _CryptoMarketContext{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCryptoMarketContext)

	if err != nil {
		return err
	}

	*o = CryptoMarketContext(varCryptoMarketContext)

	return err
}

type NullableCryptoMarketContext struct {
	value *CryptoMarketContext
	isSet bool
}

func (v NullableCryptoMarketContext) Get() *CryptoMarketContext {
	return v.value
}

func (v *NullableCryptoMarketContext) Set(val *CryptoMarketContext) {
	v.value = val
	v.isSet = true
}

func (v NullableCryptoMarketContext) IsSet() bool {
	return v.isSet
}

func (v *NullableCryptoMarketContext) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCryptoMarketContext(val *CryptoMarketContext) *NullableCryptoMarketContext {
	return &NullableCryptoMarketContext{value: val, isSet: true}
}

func (v NullableCryptoMarketContext) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCryptoMarketContext) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
